#include "SkyStackBlock.h"

#include "Components/StaticMeshComponent.h"
#include "Engine/CollisionProfile.h"
#include "Engine/StaticMesh.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "UObject/ConstructorHelpers.h"

namespace
{
	/** Materials generated by Content/Python/init_unreal.py. Loaded on first use and cached; optional. */
	UMaterialInterface* FindGeneratedMaterial(const TCHAR* Path, TWeakObjectPtr<UMaterialInterface>& Cache, bool& bMissing)
	{
		if (UMaterialInterface* Cached = Cache.Get())
		{
			return Cached;
		}
		if (bMissing)
		{
			return nullptr;
		}
		UMaterialInterface* Loaded = LoadObject<UMaterialInterface>(nullptr, Path, nullptr, LOAD_NoWarn | LOAD_Quiet);
		bMissing = Loaded == nullptr;
		if (bMissing)
		{
			UE_LOG(LogTemp, Warning, TEXT("SkyStack: %s not found. Open the project in the editor once so init_unreal.py can build it."), Path);
		}
		Cache = Loaded;
		return Loaded;
	}

	UMaterialInterface* GetBlockMaterial()
	{
		static TWeakObjectPtr<UMaterialInterface> Cache;
		static bool bMissing = false;
		return FindGeneratedMaterial(TEXT("/Game/SkyStack/M_SkyBlock.M_SkyBlock"), Cache, bMissing);
	}

	UMaterialInterface* GetGlowMaterial()
	{
		static TWeakObjectPtr<UMaterialInterface> Cache;
		static bool bMissing = false;
		return FindGeneratedMaterial(TEXT("/Game/SkyStack/M_SkyGlow.M_SkyGlow"), Cache, bMissing);
	}
}

ASkyStackBlock::ASkyStackBlock()
{
	PrimaryActorTick.bCanEverTick = true;
	PrimaryActorTick.bStartWithTickEnabled = false;

	Mesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Mesh"));
	RootComponent = Mesh;
	Mesh->SetMobility(EComponentMobility::Movable);
	Mesh->SetCollisionProfileName(UCollisionProfile::BlockAll_ProfileName);
	Mesh->SetGenerateOverlapEvents(false);

	static ConstructorHelpers::FObjectFinder<UStaticMesh> CubeFinder(TEXT("/Engine/BasicShapes/Cube.Cube"));
	static ConstructorHelpers::FObjectFinder<UMaterialInterface> FallbackFinder(TEXT("/Engine/BasicShapes/BasicShapeMaterial.BasicShapeMaterial"));

	if (CubeFinder.Succeeded())
	{
		Mesh->SetStaticMesh(CubeFinder.Object);
	}
	FallbackMaterial = FallbackFinder.Object;
}

void ASkyStackBlock::SetBlockSize(const FVector& InSize)
{
	Size = InSize;
	TweenDuration = 0.f;
	ApplyScale(FVector::OneVector);
}

void ASkyStackBlock::SetColor(const FLinearColor& InColor)
{
	Color = InColor;
	if (!Material)
	{
		BlockMaterial = GetBlockMaterial();
		UMaterialInterface* Parent = BlockMaterial ? BlockMaterial.Get() : FallbackMaterial.Get();
		Material = UMaterialInstanceDynamic::Create(Parent ? Parent : Mesh->GetMaterial(0), this);
		if (Material)
		{
			Mesh->SetMaterial(0, Material);
			Material->SetVectorParameterValue(TEXT("Size"), FLinearColor(Size.X, Size.Y, Size.Z, 0.f));
		}
	}
	if (Material)
	{
		// Both M_SkyBlock and the BasicShapeMaterial fallback expose "Color".
		Material->SetVectorParameterValue(TEXT("Color"), Color);
	}
}

void ASkyStackBlock::UseGlowMaterial(float Intensity)
{
	bGlowMaterial = true;
	Mesh->SetCastShadow(false);
	DisableCollision();
	GlowMaterial = GetGlowMaterial();
	BlockMaterial = GetBlockMaterial();
	UMaterialInterface* Parent = GlowMaterial ? GlowMaterial.Get() : (BlockMaterial ? BlockMaterial.Get() : FallbackMaterial.Get());
	Material = UMaterialInstanceDynamic::Create(Parent, this);
	if (Material)
	{
		Mesh->SetMaterial(0, Material);
		Material->SetVectorParameterValue(TEXT("Color"), Color);
		Material->SetScalarParameterValue(TEXT("Intensity"), Intensity);
		// When M_SkyGlow is missing, at least make the block version shine.
		Material->SetScalarParameterValue(TEXT("Glow"), Intensity);
	}
}

void ASkyStackBlock::SetGlowOpacity(float Opacity)
{
	if (Material)
	{
		Material->SetScalarParameterValue(TEXT("Opacity"), Opacity);
	}
}

void ASkyStackBlock::SetEdgeGlow(float InEdgeGlow)
{
	if (Material && !bGlowMaterial)
	{
		Material->SetScalarParameterValue(TEXT("EdgeGlow"), InEdgeGlow);
	}
}

void ASkyStackBlock::Flash(float Amount, float Duration)
{
	if (bGlowMaterial)
	{
		return;
	}
	FlashAmount = Amount;
	FlashDuration = FMath::Max(Duration, KINDA_SMALL_NUMBER);
	FlashTime = 0.f;
	WakeUp();
}

void ASkyStackBlock::DisableCollision()
{
	Mesh->SetCollisionEnabled(ECollisionEnabled::NoCollision);
}

void ASkyStackBlock::SetCastsShadow(bool bCastShadow)
{
	Mesh->SetCastShadow(bCastShadow);
}

void ASkyStackBlock::MakeDebris(const FVector& LinearVelocity, const FVector& AngularVelocityDeg)
{
	// Settle any running animation so the physics body matches what the player sees.
	if (TweenDuration > 0.f)
	{
		Size = TweenTarget;
		TweenDuration = 0.f;
	}
	SquashTime = -1.f;
	ApplyScale(FVector::OneVector);

	Mesh->SetCollisionProfileName(UCollisionProfile::PhysicsActor_ProfileName);
	Mesh->SetSimulatePhysics(true);
	Mesh->SetPhysicsLinearVelocity(LinearVelocity);
	Mesh->SetPhysicsAngularVelocityInDegrees(AngularVelocityDeg);
}

void ASkyStackBlock::Launch(const FVector& InVelocity, const FRotator& InSpin)
{
	DisableCollision();
	bBallistic = true;
	Velocity = InVelocity;
	Spin = InSpin;
	WakeUp();
}

void ASkyStackBlock::Squash(float Amount)
{
	SquashAmount = Amount;
	SquashTime = 0.f;
	WakeUp();
}

void ASkyStackBlock::TweenSize(const FVector& Target, float Duration, bool bDestroyWhenDone)
{
	TweenFrom = Size;
	TweenTarget = Target;
	TweenDuration = FMath::Max(Duration, KINDA_SMALL_NUMBER);
	TweenTime = 0.f;
	bDestroyAfterTween = bDestroyWhenDone;
	WakeUp();
}

void ASkyStackBlock::ShrinkAway(float Duration)
{
	ShrinkDuration = FMath::Max(Duration, KINDA_SMALL_NUMBER);
	ShrinkTime = 0.f;
	WakeUp();
}

void ASkyStackBlock::WakeUp()
{
	SetActorTickEnabled(true);
}

void ASkyStackBlock::ApplyScale(const FVector& Multiplier)
{
	const FVector Visual = Size * Multiplier;
	SetActorScale3D(Visual / 100.0);
	if (Material && !bGlowMaterial)
	{
		// The seam shader needs the real world size to keep edges a constant width.
		Material->SetVectorParameterValue(TEXT("Size"), FLinearColor(Visual.X, Visual.Y, Visual.Z, 0.f));
	}
}

void ASkyStackBlock::Tick(float DeltaSeconds)
{
	Super::Tick(DeltaSeconds);

	bool bBusy = false;
	FVector Multiplier = FVector::OneVector;

	if (TweenDuration > 0.f)
	{
		TweenTime += DeltaSeconds;
		const float Alpha = FMath::Clamp(TweenTime / TweenDuration, 0.f, 1.f);
		const float Eased = 1.f - FMath::Pow(1.f - Alpha, 3.f);
		Size = FMath::Lerp(TweenFrom, TweenTarget, static_cast<double>(Eased));
		if (Alpha >= 1.f)
		{
			TweenDuration = 0.f;
			if (bDestroyAfterTween)
			{
				Destroy();
				return;
			}
		}
		else
		{
			bBusy = true;
		}
	}

	if (SquashTime >= 0.f)
	{
		SquashTime += DeltaSeconds;
		// Damped spring: squash down, overshoot up, settle.
		const float Wobble = SquashAmount * FMath::Exp(-SquashTime * 9.f) * FMath::Cos(SquashTime * 32.f);
		Multiplier.Z = 1.0 - Wobble;
		Multiplier.X = 1.0 + Wobble * 0.5;
		Multiplier.Y = 1.0 + Wobble * 0.5;
		if (SquashTime > 0.6f)
		{
			SquashTime = -1.f;
			Multiplier = FVector::OneVector;
		}
		else
		{
			bBusy = true;
		}
	}

	if (ShrinkDuration > 0.f)
	{
		ShrinkTime += DeltaSeconds;
		const float Alpha = ShrinkTime / ShrinkDuration;
		if (Alpha >= 1.f)
		{
			Destroy();
			return;
		}
		Multiplier *= static_cast<double>(1.f - Alpha * Alpha);
		bBusy = true;
	}

	if (FlashDuration > 0.f)
	{
		FlashTime += DeltaSeconds;
		const float Alpha = FMath::Clamp(FlashTime / FlashDuration, 0.f, 1.f);
		if (Material)
		{
			Material->SetScalarParameterValue(TEXT("Glow"), FlashAmount * FMath::Square(1.f - Alpha));
		}
		if (Alpha >= 1.f)
		{
			FlashDuration = 0.f;
		}
		else
		{
			bBusy = true;
		}
	}

	if (bBallistic)
	{
		Velocity.Z -= 2200.0 * DeltaSeconds;
		AddActorWorldOffset(Velocity * DeltaSeconds);
		AddActorWorldRotation(Spin * DeltaSeconds);
		bBusy = true;
	}

	if (!Mesh->IsSimulatingPhysics())
	{
		ApplyScale(Multiplier);
	}

	if (!bBusy)
	{
		SetActorTickEnabled(false);
	}
}
