/**
 * Writes a service worker that precaches whatever `vite build` just emitted.
 * Generated after the build because asset filenames are content-hashed, and a
 * worker that lists stale names would serve a broken app offline.
 */
import { readdirSync, writeFileSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';

const DIST = new URL('../dist/', import.meta.url).pathname;

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

const assets = walk(DIST)
  .map((f) => './' + relative(DIST, f).split('\\').join('/'))
  .filter((f) => !f.endsWith('sw.js'));

// The cache name carries the build's own fingerprint, so a new build takes
// over instead of serving yesterday's game from disk.
const version = assets.join('|').length.toString(36) + '-' + Date.now().toString(36);

writeFileSync(
  join(DIST, 'sw.js'),
  `// Generated by scripts/make-sw.mjs — do not edit.
const CACHE = 'prism-break-${version}';
const ASSETS = ${JSON.stringify(assets, null, 2)};

self.addEventListener('install', (e) => {
  e.waitUntil(
    caches
      .open(CACHE)
      // './' as well as './index.html': launching from a home screen requests
      // the directory, and a cache holding only the filename misses it.
      .then((c) => c.addAll(['./', ...ASSETS]))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

// Cache-first for our own assets: the game is small, fully offline, and should
// never wait on a network round trip to start.
self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  if (e.request.method !== 'GET' || url.origin !== self.location.origin) return;

  // Any navigation gets the app shell, whatever path it asked for. This is what
  // makes launching from a home screen work with no network at all.
  // ignoreVary matters: the preview and production servers send Vary headers,
  // and a cached response stored by addAll will not match a later request
  // without it — which looks exactly like an empty cache.
  const opts = { ignoreSearch: true, ignoreVary: true };

  // Any navigation gets the app shell, whatever path it asked for. This is what
  // makes launching from a home screen work with no network at all.
  if (e.request.mode === 'navigate') {
    e.respondWith(
      caches
        .match('./index.html', opts)
        .then((hit) => hit || caches.match('./', opts))
        .then((hit) => hit || fetch(e.request))
        .catch(() => fetch(e.request)),
    );
    return;
  }

  e.respondWith(
    caches.match(e.request, opts).then((hit) => {
      if (hit) return hit;
      // Deliberately no index.html fallback here. Handing HTML to a request for
      // a script produces a MIME-type error that looks nothing like the cache
      // miss it actually is, which is a miserable thing to debug.
      return fetch(e.request).then((res) => {
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(e.request, copy)).catch(() => {});
        return res;
      });
    }),
  );
});
`,
);
console.log(`dist/sw.js — ${assets.length} assets precached`);
