/**
 * Writes a service worker that precaches whatever `vite build` just emitted.
 * Generated after the build because asset filenames are content-hashed, and a
 * worker that lists stale names would serve a broken app offline.
 */
import { readdirSync, writeFileSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';

const DIST = new URL('../dist/', import.meta.url).pathname;

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

const assets = walk(DIST)
  .map((f) => './' + relative(DIST, f).split('\\').join('/'))
  .filter((f) => !f.endsWith('sw.js'));

// The cache name carries the build's own fingerprint, so a new build takes
// over instead of serving yesterday's game from disk.
const version = assets.join('|').length.toString(36) + '-' + Date.now().toString(36);

writeFileSync(
  join(DIST, 'sw.js'),
  `// Generated by scripts/make-sw.mjs — do not edit.
const CACHE = 'prism-break-${version}';
const ASSETS = ${JSON.stringify(assets, null, 2)};

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

// Cache-first for our own assets: the game is small, fully offline, and should
// never wait on a network round trip to start.
self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  if (e.request.method !== 'GET' || url.origin !== self.location.origin) return;
  e.respondWith(
    caches.match(e.request).then(
      (hit) =>
        hit ||
        fetch(e.request)
          .then((res) => {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(e.request, copy)).catch(() => {});
            return res;
          })
          .catch(() => caches.match('./index.html')),
    ),
  );
});
`,
);
console.log(`dist/sw.js — ${assets.length} assets precached`);
